id: IE39E57C8
ocr_import_info:
  timestamp: '2023-09-29T16:05:27.404019+00:00'
  batch_id: batch-ef23
  ocr_engine: GoogleVisionEngine
  ocr_model_type: builtin/weekly
  ocr_lang_hint: ''
  software_id: ocr-pipelines@v0.1.11
  sponsor: Dharma Kyab
  sponsor_consent: true
  op_import_options: {}
  op_import_version: 0.11.7
default_language: bo
source: https://library.bdrc.io
initial_creation_type: ocr
imported: 2023-09-30 14:10:00.372636+00:00
last_modified: 2023-09-30 14:10:00.372644+00:00
source_metadata:
  id: http://purl.bdrc.io/resource/W21957
  status: http://purl.bdrc.io/admindata/StatusReleased
  access: http://purl.bdrc.io/admindata/AccessOpen
  reproduction_of: http://purl.bdrc.io/resource/MW21957
  copyright_status: http://purl.bdrc.io/resource/CopyrightPublicDomain
  title: གསུང་འབུམ། ཐུབ་བསྟན་བཤད་སྒྲུབ་རྒྱ་མཚོ།
  languages:
  - bo
  author: རག་མགོ་མཆོག་སྤྲུལ་ཐུབ་བསྟན་བཤད་སྒྲུབ་རྒྱ་མཚོ།
statistics:
  ocr_word_mean_confidence_index: 0.9079368699657876
  ocr_word_median_confidence_index: 0.967493465
bases:
  I1960:
    source_metadata:
      id: http://purl.bdrc.io/resource/I1960
      total_pages: 718
      volume_number: 1
      volume_pages_bdrc_intro: 2
    order: 1
    base_file: I1960.txt
    statistics:
      ocr_word_median_confidence_index: 0.96383638
      ocr_word_mean_confidence_index: 0.9047270343071523
  I1963:
    source_metadata:
      id: http://purl.bdrc.io/resource/I1963
      total_pages: 746
      volume_number: 4
      volume_pages_bdrc_intro: 2
    order: 4
    base_file: I1963.txt
    statistics:
      ocr_word_median_confidence_index: 0.95950514
      ocr_word_mean_confidence_index: 0.8974085420764206
  I1962:
    source_metadata:
      id: http://purl.bdrc.io/resource/I1962
      total_pages: 706
      volume_number: 3
      volume_pages_bdrc_intro: 2
    order: 3
    base_file: I1962.txt
    statistics:
      ocr_word_median_confidence_index: 0.97384465
      ocr_word_mean_confidence_index: 0.9153577552554961
  I1961:
    source_metadata:
      id: http://purl.bdrc.io/resource/I1961
      total_pages: 706
      volume_number: 2
      volume_pages_bdrc_intro: 2
    order: 2
    base_file: I1961.txt
    statistics:
      ocr_word_median_confidence_index: 0.9710385800000001
      ocr_word_mean_confidence_index: 0.9133738145596297
copyright:
  status: Public domain
  notice: Public domain
  info_url: https://creativecommons.org/publicdomain/mark/1.0/
license: CC0
